### ISSUE TITLE
Couldn't load plugin 'pca4cd'

### ISSUE THREAD

**Issue by ghost** [SMByC/PCA4CD#10]
Hola estimado Xavier, soy yo nuevamente solicitando tu ayuda:

Al momento de instalar el plugin PCA4CD me aparece este error que al parecer corresponde a que las carpetas no coinciden, la verdad estaría nuevamente agradecido si me pudieras ayudar, igualmente el sistema operativo es Ubuntu:

`
Couldn't load plugin 'pca4cd' due to an error when calling its classFactory() method 

RuntimeError: PCA4CD: Error installing Python packages. Read install instruction: https://smbyc.bitbucket.io/qgisplugins/pca4cd Log: Added /home/itadmin/.local/share/pca4cd/python36/local/lib/python3.6/dist-packages as module search pathAdded /home/itadmin/.local/share/pca4cd/python36/lib/python3/dist-packages as module search pathAdded /home/itadmin/.local/share/pca4cd/python36/lib/python3.6/dist-packages as module search pathPackage directory: /home/itadmin/.local/share/pca4cd/python36/usr/bin/python3 -m pip install --prefix /home/itadmin/.local/share/pca4cd/python36 dask toolz pyqtgraph==0.11.1ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations 
Traceback (most recent call last):
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pca4cd/__init__.py", line 35, in pre_init_plugin
    for msg_type, msg_val in load_install_extra_deps():
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pca4cd/utils/extra_deps.py", line 183, in load_install_extra_deps
    for line in run_subprocess(args, LOG_PATH):
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pca4cd/utils/extra_deps.py", line 246, in run_subprocess
    raise subprocess.CalledProcessError(process.returncode, args)
subprocess.CalledProcessError: Command '['/usr/bin/python3', '-m', 'pip', 'install', '--prefix', '/home/itadmin/.local/share/pca4cd/python36', 'dask', 'toolz', 'pyqtgraph==0.11.1']' returned non-zero exit status 1.

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3/dist-packages/qgis/utils.py", line 334, in _startPlugin
    plugins[packageName] = package.classFactory(iface)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pca4cd/__init__.py", line 61, in classFactory
    pre_init_plugin(iface)
  File "/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/pca4cd/__init__.py", line 50, in pre_init_plugin
    'https://smbyc.bitbucket.io/qgisplugins/pca4cd\nLog:\n' + log) from e
RuntimeError: 
PCA4CD: Error installing Python packages. Read install instruction: https://smbyc.bitbucket.io/qgisplugins/pca4cd
Log:
Added /home/itadmin/.local/share/pca4cd/python36/local/lib/python3.6/dist-packages as module search pathAdded /home/itadmin/.local/share/pca4cd/python36/lib/python3/dist-packages as module search pathAdded /home/itadmin/.local/share/pca4cd/python36/lib/python3.6/dist-packages as module search pathPackage directory: /home/itadmin/.local/share/pca4cd/python36/usr/bin/python3 -m pip install --prefix /home/itadmin/.local/share/pca4cd/python36 dask toolz pyqtgraph==0.11.1ERROR: Can not combine '--user' and '--prefix' as they imply different installation locations

`

Python version: 3.6.9 (default, Jan 26 2021, 15:33:00) [GCC 8.4.0] 
QGIS version: 3.16.3-Hannover Hannover, 94ac9f21b8 

Python Path:
/usr/share/qgis/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins
/usr/share/qgis/python/plugins
/usr/lib/python36.zip
/usr/lib/python3.6
/usr/lib/python3.6/lib-dynload
/usr/local/lib/python3.6/dist-packages
/usr/lib/python3/dist-packages
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin
/home/itadmin/.local/share/QGIS/QGIS3/profiles/default/python/plugins/vrtbuilderplugin/vrtbuilder
/home/itadmin/.local/share/pca4cd/python36/local/lib/python3.6/dist-packages
/home/itadmin/.local/share/pca4cd/python36/lib/python3/dist-packages
/home/itadmin/.local/share/pca4cd/python36/lib/python3.6/dist-packages

Muchas gracias!

**Comment by XavierCLL** [comment]
Hola Harold,

PCA4CD necesita de un paquete para graficar, el paquete intenta de instalarlo de manera local en el usuario si el sistema no lo tiene instalado, pero si se puede instalar ese paquete en el sistema es mucho mejor y en Linux es muy facil, instala en Ubuntu el paquete `pyqtgraph`:

`sudo apt install python3-pyqtgraph`

reinicias Qgis y el complemento, me cuentas como te va.

**Comment by leonharol** [comment]
Hola Xavier, presento el mismo error... Pero igual muchas gracias por la respuesta

**Comment by XavierCLL** [comment]
Hola Harold, 
Garantiza que puedas importar pyqtgraph en una terminal del sistema de python3.6 `import pyqtgraph`. El error literal es que estas usando una vieja version de pip para instalar esa libreria, tenerlo en el sistema evita intentar instalarlo, el error que tienes no pasa en versiones mas recientes de python y pip. Saludos

**Comment by pgarcia2021** [comment]
Saludos Xavier y Harold, 

Les cuento que presenté el mismo error al dar en actulizar complementos. Luego de algún tiempo realizando las actualizaciones de paquetes de python y otras recomendaciones que daban por diferentes sitios, recorde que el paquete lo había instalado desde el archivo .zip, lo cual realicé nuevamente y funciona sin ningún problema. Saludos.

**Comment by XavierCLL** [comment]
En la ultima version 23.2 porfin pude incluir todas las librerias necesarias internamente dentro del paquete sin necesidad de instalar ninguna dependencia, para sistemas Linux, Mac y Windows.
