### ISSUE TITLE
PCA4CD error 

### ISSUE THREAD

**Issue by spalaciosno** [SMByC/PCA4CD#8]
![Captura](https://user-images.githubusercontent.com/39316668/109093611-a522a980-76e6-11eb-9a0e-939c3ab75501.JPG)

Este es el mesaje de los detalles del error:

Traceback (most recent call last):
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
    return func(*args, **kwargs)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 86, in wrapper
    obj_returned = func(*args, **kwargs)
  File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\component_analysis_dialog.py", line 470, in aoi_changes
    self.aoi_features.addFeature(new_feature)
  File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\core\additions\edit.py", line 44, in __exit__
    raise QgsEditError(self.layer.commitErrors())
qgis.core.additions.edit.QgsEditError: ['ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.']

**Comment by spalaciosno** [comment]
> ![Captura](https://user-images.githubusercontent.com/39316668/109093611-a522a980-76e6-11eb-9a0e-939c3ab75501.JPG)
> 
> Este es el mesaje de los detalles del error:
> 
> Traceback (most recent call last):
> File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
> return func(*args, **kwargs)
> File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 86, in wrapper
> obj_returned = func(*args, **kwargs)
> File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\component_analysis_dialog.py", line 470, in aoi_changes
> self.aoi_features.addFeature(new_feature)
> File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\core\additions\edit.py", line 44, in **exit**
> raise QgsEditError(self.layer.commitErrors())
> qgis.core.additions.edit.QgsEditError: ['ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.']

El error se presenta en la versión 3.13.3 de Qgis

**Comment by spalaciosno** [comment]
> > ![Captura](https://user-images.githubusercontent.com/39316668/109093611-a522a980-76e6-11eb-9a0e-939c3ab75501.JPG)
> > Este es el mesaje de los detalles del error:
> > Traceback (most recent call last):
> > File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 36, in wrapper
> > return func(*args, **kwargs)
> > File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\utils\system_utils.py", line 86, in wrapper
> > obj_returned = func(*args, **kwargs)
> > File "C:/Users/Usuario/AppData/Roaming/QGIS/QGIS3\profiles\default/python/plugins\pca4cd\gui\component_analysis_dialog.py", line 470, in aoi_changes
> > self.aoi_features.addFeature(new_feature)
> > File "C:/PROGRA~1/QGIS3~1.16/apps/qgis/./python\qgis\core\additions\edit.py", line 44, in **exit**
> > raise QgsEditError(self.layer.commitErrors())
> > qgis.core.additions.edit.QgsEditError: ['ERROR: 1 feature(s) not added - geometry type is not compatible with the current layer.']
> 
> El error se presenta en la versión 3.16.3 de Qgis

**Comment by XavierCLL** [comment]
Hola, @spalaciosno, cuando tengas la oportunidad puedes verificar el arreglo de este error instalando el siguiente zip con los ultimos cambios (para reisntalar el plugin desde este archivo zip es ir a la ventana de complementos y luego ir instalar desde archivo zip), gracias!

[pca4cd.zip](https://github.com/SMByC/PCA4CD/files/6056188/pca4cd.zip)

**Comment by spalaciosno** [comment]
Hola Xavier, reinstale el plugin y pude usarlo sin problemas, pude tomar las muestras y exportar la información sin problemas. Voy a seguir usándolo y si encuentro algún problema lo reporto.

Gracias

**Comment by XavierCLL** [comment]
Gracias Santiago!
